version: '3'

services:
  starhub-tg-bot:
    # build: '.'
    image: registry.gitlab.com/vantablack/starhub-telegram-bot:latest
    container_name: starhub-tg-bot
    volumes:
      - './config:/app/config:ro'
    # networks:
    #   - traefik-proxy
    # labels:
    #   - "traefik.frontend.rule=Host:yourdomain.com"
    #   - "traefik.enable=true"
    #   - "traefik.port=80"
    #   - "traefik.docker.network=traefik-proxy"
# networks:
#   traefik-proxy:
#     external: true