version: '3'
services:
  starhub-tg-bot:
    build: '.'
    image: starhub-tg-bot:latest
    container_name: starhub-tg-bot
    volumes:
      - './config:/app/config:ro'
   environment:
     - VIRTUAL_HOST=bot.chongyaowei.me
     - LETSENCRYPT_HOST=bot.chongyaowei.me
     - LETSENCRYPT_EMAIL=chongyaowei@gmail.com
networks:
 default:
   external:
     name: webproxy